name: Development Workflow

on:
  push:
    branches:
      - dev

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: First step
        run: echo "Hello"
      - name: Second step
        run: echo "Ramakrishna"
  